# Generated by Django 2.0.9 on 2018-12-09 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accionInm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Describir cómo se trato corregir la acción que genera la NC, en una prímera instancia')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cierreNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(help_text='Informar sobre algo especial en el cierre de NC')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código propio del sistema.', max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechaApertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaSuceso', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False, help_text='Indica si la NC está cerrada.')),
                ('accInm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.accionInm')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cierrenc',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.nC'),
        ),
    ]
